implemented scroll
Neemahj/page-feeds pull request #2
Opened 2022-06-24 08:57 UTC by Neemahj

2022-06-26 16:49 UTC, Asylcreek requested changes
Keep in mind that you are not preventing fetching blog posts when there are no more blog posts to fetch

2022-06-26 16:49 UTC, Asylcreek commented on src/components/BlogPage.js
> +      if ((page != null) && (page > 1)) {
Is `page` ever going to be `null`?

2022-06-26 16:49 UTC, Asylcreek commented on src/components/BlogPage.js
> +  }
Rewrite this without tying it to the `window` object.

Use event listeners in your `useEffect`

2022-06-26 16:49 UTC, Asylcreek commented on src/components/BlogPage.js
> +          if(!(displayBlogs)){
`displayBlogs` is array by default, it is always **truthy**, you should be checking it's length instead

2022-06-26 16:49 UTC, Asylcreek commented on src/components/BlogPage.js
> +          setDisplayBlogs((previousPost)=> [...previousPost, ...displayBlogs])
If `getBlog` already sets `displayBlogs` why then are you calling `setDisplayBlogs` again?

2022-06-26 16:49 UTC, Asylcreek commented on src/components/BlogPage.js
> +  const loadBlogs = (page) => {
Move `loadBlogs` into the `useEffect`

2022-06-27 12:28 UTC, Neemahj commented on src/components/BlogPage.js
> +  const loadBlogs = (page) => {
okay sir

2022-06-28 15:01 UTC, Neemahj commented on src/components/BlogPage.js
> +      if ((page != null) && (page > 1)) {
yes sir

2022-08-19 20:33 UTC, Asylcreek approved these changes

2022-12-30 07:48 UTC, merged